FROM cassandra:2.1

# COPY ./init /etc/cassandra/init

# Require user & pass for accessing Cassandra instance within container
# Change to use sed over echo, as this config item already exists
# RUN echo "authenticator: PasswordAuthenticator" >> /etc/cassandra/cassandra.yaml

